backend:
  name: github
  repo: raphaelsanchez/lanefpassion
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "cuisines"
    label: "Cuisines"
    folder: "content/cuisines"
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}

  - name: "settings"
    label: "Paramètres"
    files:
      - name: "global"
        label: "Réglages globaux"
        file: settings/global.json
        editor:
          preview: false
        fields:
          - label: "Adresse"
            name: "address"
            widget: "object"
            fields:
              - {label: Street, name: street, widget: string}
              - {label: CP, name: zip, widget: string}
              - {label: Ville, name: city, widget: string}

          # Contact
          - label: "Contact"
            name: "contact"
            widget: "object"
            fields:
              - {label: Téléphone, name: phone, widget: string}
              - {label: Email, name: email, widget: string}

          # Réseaux sociaux
          - label: "Réseaux sociaux"
            name: "social"
            widget: "object"
            fields:
              - {label: Facebook, name: facebook, widget: string}
              - {label: Instagram, name: instagram, widget: string}
              - {label: LinkedIn, name: linkedin, widget: string}

      - label: "Menus"
        name: "menus"
        widget: "object"
        file: settings/menus.json
        editor:
          preview: false
        summary: 'Ajouter vos réseaux sociaux'
        fields:
          - {label: Facebook, name: facebook, widget: string}
          - {label: Instagram, name: instagram, widget: string}
          - {label: LinkedIn, name: linkedin, widget: string}
          - {label: Pinterest, name: pinterest, widget: string}


