backend:
  name: github
  repo: raphaelsanchez/lanefpassion
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  # Les cuisines
  - name: "cuisines"
    label: "Cuisines"
    folder: "content/cuisines"
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Soustitre", name: "subtitle", widget: "string"}
      - {label: "Image", name: "cover", widget: "image"}
      - {label: "Contenu", name: "body", widget: "markdown"}

  # Les partenaires
  - label: "Partenaires"
    name: "partenaires"
    folder: "content/partenaires"
    slug: "{{slug}}"
    summary: "{{title}}"
    editor:
      preview: false
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Image", name: "cover", widget: "image"}
      - {label: "Lien", name: "url", widget: "string"}

  # Les réglages
  - name: "settings"
    label: "Paramètres"
    files:
      - name: "global"
        label: "Réglages globaux"
        file: settings/global.json
        editor:
          preview: false
        fields:
          - label: "Adresse"
            name: "address"
            widget: "object"
            fields:
              - {label: Street, name: street, widget: string}
              - {label: CP, name: zip, widget: string}
              - {label: Ville, name: city, widget: string}

          # Contact
          - label: "Contact"
            name: "contact"
            widget: "object"
            fields:
              - {label: Téléphone, name: phone, widget: string}
              - {label: Email, name: email, widget: string}

          # Réseaux sociaux
          - label: "Réseaux sociaux"
            name: "social"
            widget: "object"
            fields:
              - {label: Facebook, name: facebook, widget: string}
              - {label: Instagram, name: instagram, widget: string}
              - {label: Pinterest, name: pinterest, widget: string}
              - {label: LinkedIn, name: linkedin, widget: string}

      - label: "Menus"
        name: "menus"
        file: settings/menus.json
        fields:
          - name: nav-primary
            label: Menu principal
            label_singular: 'Menu'
            widget: list
            fields:
              - { name: 'name', label: 'Label', widget: 'string'}
              - { name: 'href', label: 'Url', widget: 'string'}


